// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqmesiajuftzqcizxoqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbWVzaWFqdWZ0enFjaXp4b3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjUyNjgsImV4cCI6MjA2MTEwMTI2OH0.n9b6ntMqT7h4k_v0LKP8Ns8Htc6DRyn5i8eIEeRbKao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);